### ISSUE TITLE
Analyzing project with QT

### ISSUE THREAD

**Issue by zonda85** [rettichschnidi/clang-misracpp2008#25]
Hi, 
I'm trying to use your plugin in a project which uses the QT library.
Clang compiles fine the project, but when I enable the plugin add this command line i get a lot of errors.

``` javascript
QMAKE_CXXFLAGS += -Xclang -load -Xclang /usr/local/lib/misracpp2008.so -Xclang -add-plugin -Xclang misra.cpp.2008 -Xclang -plugin-arg-misra.cpp.2008 -Xclang all
```

The errors are referred to the file /usr/include/qt4/QtCore/qglobal.h so it's part of the QT library and not my code. 

How can I exclude the library header files? Is there any workaround or fix?

Thanks

**Comment by rettichschnidi** [comment]
You can try to use the  [--exclude-path](https://github.com/rettichschnidi/clang-misracpp2008/blob/bdb6e092029e76c9f095d118e8521fa6d7dda442/src/misracpp2008.cpp#L216) argument which takes a regex as value.

Example: `-Xclang -plugin-arg-misra.cpp.2008 -Xclang --exclude-path='/usr/include/qt4/'`

However, I am pretty sure that using clang-misracpp2008 on a Qt project will result in tons of other problems. I have never tested it and I doubt that it makes sense for many (most!?) MISRA C++ rules to be applied to Qt projects.
